/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/_ws_types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * [CODEGEN ONLY] WS event type registry
     * @description This endpoint exists ONLY to surface WebSocket payload types into OpenAPI components.schemas for openapi-typescript codegen (D-27, Pitfall 3). It is never called at runtime.
     */
    get: operations["_ws_type_registry__ws_types_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ArbOpp
     * @description Cross-vault arbitrage opportunity detected by the backend block-watcher (D-74).
     *
     *     direction: 'mint' = NAV < AMM (arber profits by minting at NAV, selling at AMM premium).
     *                'burn' = NAV > AMM (arber profits by buying at AMM discount, burning at NAV).
     *     gapBps: |NAV - AMM| / NAV in basis points (1 bps = 0.01%).
     */
    ArbOpp: {
      /**
       * Vault Address
       * @description Vault with the NAV-AMM gap
       */
      vault_address: string;
      /**
       * Nav Price
       * @description NAV per mTOKEN in 1e18 scale (uint256 as string)
       */
      nav_price: string;
      /**
       * Amm Price
       * @description Camelot AMM price in 1e18 scale (uint256 as string)
       */
      amm_price: string;
      /**
       * Gap Bps
       * @description Absolute gap in basis points
       */
      gap_bps: number;
      /**
       * Direction
       * @description Arbitrage direction
       * @enum {string}
       */
      direction: "mint" | "burn";
    };
    /**
     * CurrentState
     * @description Snapshot bundle sent on every subscribe (initial + reconnect) for a vault (D-24).
     *
     *     Read from backend.dashboard_model_state materialized view.
     *     Carries its own seq so the client baseline is anchored immediately.
     *     recentTrades: last N trades (typically 10-20 for initial render).
     *     latestJournal: most recent JournalEvent for this vault (null if no trades yet).
     */
    CurrentState: {
      /**
       * Vault Address
       * @description Vault this snapshot covers
       */
      vault_address: string;
      /** @description Most recent NavTick for this vault */
      latest_nav: components["schemas"]["NavTick"];
      /**
       * Recent Trades
       * @description Recent trades (capped array)
       */
      recent_trades?: components["schemas"]["TradeEvent"][];
      /** @description Most recent journal entry; null if none */
      latest_journal?: components["schemas"]["JournalEvent"] | null;
      /** @description Current model operational status */
      model_status: components["schemas"]["ModelStatus"];
      /**
       * Seq
       * @description Snapshot seq — client baseline for per-channel monotonic ordering (D-25)
       */
      seq: number;
    };
    /**
     * Envelope
     * @description Standard WS event envelope (D-26).
     *
     *     Every event sent over ws/vault/* or ws/global is wrapped in this envelope.
     *
     *     seq: per-channel monotonic sequence number (D-25). Client drops if seq <= lastAppliedSeq.
     *     serverTs: ISO 8601 UTC timestamp at event emission (indexer server time).
     *     chainTs: ISO 8601 UTC block timestamp; null for purely operational events (ModelStatus, SessionEvent).
     *     blockNumber: block number; null for purely operational events.
     *     latestBlockNumber / latestBlockTs: filled for purely operational events that carry no chain anchor.
     *     eventType: discriminator string — matches the class name of the payload model.
     *     payload: the serialized event model (dict, pre-validated by the emitter).
     *
     *     Dashboard computes indexer lag as (serverTs - chainTs) with banner thresholds:
     *       testnet: banner at 15s; mainnet: banner at 5s (D-26).
     */
    Envelope: {
      /**
       * Seq
       * @description Per-channel monotonic sequence number (D-25)
       */
      seq: number;
      /**
       * Server Ts
       * @description ISO 8601 UTC emission timestamp (server clock)
       */
      server_ts: string;
      /**
       * Chain Ts
       * @description ISO 8601 UTC block timestamp; null for operational events
       */
      chain_ts?: string | null;
      /**
       * Block Number
       * @description Block number; null for operational events
       */
      block_number?: number | null;
      /**
       * Event Type
       * @description Payload discriminator (class name of the event model)
       */
      event_type: string;
      /**
       * Payload
       * @description Serialized event model payload (dict)
       */
      payload: unknown;
      /**
       * Latest Block Number
       * @description Latest known block; filled for operational events
       */
      latest_block_number?: number | null;
      /**
       * Latest Block Ts
       * @description Latest known block ts (ISO 8601 UTC); filled for operational events
       */
      latest_block_ts?: string | null;
    };
    /**
     * JournalEvent
     * @description Emitted when a journal entry's state transitions (D-21 state machine).
     *
     *     Carries the current journal_state so the frontend can show pin progress.
     *     pinata_cid / web3_storage_cid are null until the respective pin completes.
     */
    JournalEvent: {
      /**
       * Vault Address
       * @description Vault associated with this journal entry
       */
      vault_address: string;
      /**
       * Trade Hash
       * @description Journal entry trade hash (bytes32 as hex)
       */
      trade_hash: string;
      /**
       * Pinata Cid
       * @description Pinata IPFS CID; null until pinned_primary
       */
      pinata_cid?: string | null;
      /**
       * Web3 Storage Cid
       * @description web3.storage CID; null until pinned_backup
       */
      web3_storage_cid?: string | null;
      /** @description Current state machine state (D-21) */
      journal_state: components["schemas"]["JournalStateEnum"];
    };
    /**
     * JournalStateEnum
     * @description Mirrors the journal_state Postgres ENUM defined in Plan 03 migrations (D-21).
     * @enum {string}
     */
    JournalStateEnum:
      | "pending_pin"
      | "pinned_primary"
      | "pinned_backup"
      | "signed"
      | "submitted"
      | "recorded"
      | "failed";
    /**
     * ModelStatus
     * @description Emitted when an LLM model's operational status changes (ORCH-06 circuit-breaker).
     *
     *     model: the provider model string (e.g. 'claude-opus-4-7').
     *     status: active | paused | malformed  (maps to ORCH-06 enum).
     *     consecutiveFailures: counter incremented on validation/timeout failures; resets on success.
     *     reason: optional human-readable note (e.g. 'malformed JSON response: missing action field').
     */
    ModelStatus: {
      /**
       * Vault Address
       * @description Vault managed by this model
       */
      vault_address: string;
      /**
       * Model
       * @description LLM model identifier (e.g. 'claude-opus-4-7')
       */
      model: string;
      /** @description Operational status */
      status: components["schemas"]["ModelStatusEnum"];
      /**
       * Consecutive Failures
       * @description Consecutive validation/timeout failures
       * @default 0
       */
      consecutive_failures: number;
      /**
       * Reason
       * @description Human-readable status note
       */
      reason?: string | null;
    };
    /**
     * ModelStatusEnum
     * @description Model operational status — supports ORCH-06 downstream (circuit-breaker).
     * @enum {string}
     */
    ModelStatusEnum: "active" | "paused" | "malformed";
    /**
     * NavTick
     * @description Per-block NAV snapshot for one vault.
     *
     *     navPerToken1e18: uint256 NAV-per-share scaled to 1e18 (string for bigint-safety).
     *     totalAssets: total USDC in the vault (string, 6-decimal USDC units, bigint-safe).
     *     ammPrice: Camelot AMM price for mTOKEN in the same 1e18 scale; nullable before pool seeded.
     */
    NavTick: {
      /**
       * Vault Address
       * @description ERC-4626 vault contract address
       */
      vault_address: string;
      /**
       * Nav Per Token 1E18
       * @description NAV per mTOKEN share scaled to 1e18 (uint256 as string)
       */
      nav_per_token_1e18: string;
      /**
       * Total Assets
       * @description Total USDC in vault, 6-decimal (uint256 as string)
       */
      total_assets: string;
      /**
       * Block Number
       * @description Block number at which NAV was computed
       */
      block_number: number;
      /**
       * Amm Price
       * @description Camelot AMM price (1e18 scale); null before pool seeded
       */
      amm_price?: string | null;
    };
    /**
     * SessionEvent
     * @description Lifecycle events for a trading session.
     *
     *     kind: 'started' | 'hour_milestone' | 'settling' | 'settled'.
     *     hour: non-null only for 'hour_milestone' kind (e.g. 24, 48).
     */
    SessionEvent: {
      /**
       * Session Id
       * @description Unique session identifier
       */
      session_id: string;
      /**
       * Kind
       * @description Session lifecycle event kind
       * @enum {string}
       */
      kind: "started" | "hour_milestone" | "settling" | "settled";
      /**
       * Hour
       * @description Session hour; non-null only for hour_milestone
       */
      hour?: number | null;
    };
    /**
     * TradeEvent
     * @description Emitted when the orchestrator executes (or cancels) a position on GMX / MockPerps.
     *
     *     action: 'open' | 'close' | 'adjust'  (D-05 action field subset).
     *     market: 'ETH' | 'BTC' | 'SOL'  (D-10 enumerated markets).
     *     sizeUsd: notional position size in USD (string for precision).
     *     leverage: effective leverage (float, 1.0..3.0 per spec 3x cap).
     *     txHash: the keeper-execution tx hash (from OrderExecuted event), NOT createOrder tx.
     */
    TradeEvent: {
      /**
       * Vault Address
       * @description Vault that owns this position
       */
      vault_address: string;
      /**
       * Order Key
       * @description GMX / MockPerps orderKey (bytes32 as hex string)
       */
      order_key: string;
      /**
       * Action
       * @description Trade action
       * @enum {string}
       */
      action: "open" | "close" | "adjust";
      /**
       * Market
       * @description Perpetual market
       * @enum {string}
       */
      market: "ETH" | "BTC" | "SOL";
      /**
       * Side
       * @description Position direction
       * @enum {string}
       */
      side: "long" | "short";
      /**
       * Size Usd
       * @description Notional size in USD (string for precision)
       */
      size_usd: string;
      /**
       * Leverage
       * @description Effective leverage (1.0..3.0)
       */
      leverage: number;
      /**
       * Tx Hash
       * @description On-chain transaction hash from keeper execution
       */
      tx_hash: string;
      /**
       * Block Number
       * @description Block number of execution
       */
      block_number: number;
      /**
       * Trade Hash
       * @description Journal trade hash (bytes32 as hex); populated after journal pinned
       */
      trade_hash?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  _ws_type_registry__ws_types_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["NavTick"]
            | components["schemas"]["TradeEvent"]
            | components["schemas"]["JournalEvent"]
            | components["schemas"]["ModelStatus"]
            | components["schemas"]["ArbOpp"]
            | components["schemas"]["SessionEvent"]
            | components["schemas"]["CurrentState"]
            | components["schemas"]["Envelope"];
        };
      };
    };
  };
}
