"""
Alembic env.py — single Alembic tree managing two Postgres schemas:
  - orchestrator  (source of truth: sessions, trades, journal_entries, nav_snapshots, …)
  - backend       (materialized views, websocket_sessions, verifier_replay_log)

Key design decisions (D-22 / RESEARCH.md Pattern 3):
  - ONE `alembic upgrade head` manages BOTH schemas.
  - Before running migrations we CREATE SCHEMA IF NOT EXISTS for both schemas so the
    target schemas exist even on a fresh database.
  - `version_table_schema="orchestrator"` keeps the single alembic_version table in the
    orchestrator schema (Assumption A1 from RESEARCH.md: simpler than truly separate
    per-schema history; matches D-22 "single tree" intent).
  - `include_schemas=True` allows ops to name schemas explicitly.
  - `target_metadata=None` — ALL DDL is hand-written via op.execute / op.create_table
    with explicit schema=.  Autogenerate is intentionally NOT used (BRIN indexes,
    materialized views, ENUMs, and triggers cannot be autogenerated).
  - DATABASE_URL must be a synchronous psycopg/psycopg2 URL for Alembic.
    Runtime services use asyncpg. Example:
      postgresql+psycopg://migrator_user:pass@localhost:5432/traider
"""

import os
import logging
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool, text
from alembic import context

# Alembic Config object — gives access to alembic.ini values.
config = context.config

# Set up Python logging from alembic.ini [loggers] section (if present).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# All DDL is hand-written via op.execute; autogenerate is explicitly disabled (D-22).
# target_metadata=None signals to Alembic that autogenerate is not in use.
target_metadata = None

# ---------------------------------------------------------------------------
# Resolve DATABASE_URL from environment.
# We do NOT commit credentials into alembic.ini; sqlalchemy.url is left blank there.
# ---------------------------------------------------------------------------


def get_database_url() -> str:
    """Read DATABASE_URL from the environment.

    The URL must be a synchronous psycopg/psycopg2 connection string.
    asyncpg URLs (postgresql+asyncpg://...) are used by runtime services only.

    Example:
        postgresql+psycopg://migrator_user:pass@localhost:5432/traider
        postgresql://migrator_user:pass@localhost:5432/traider   (psycopg2 default)
    """
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL environment variable is not set.\n"
            "Set it to a synchronous psycopg URL before running alembic, e.g.:\n"
            "  export DATABASE_URL=postgresql+psycopg://migrator_user:pass@localhost:5432/traider\n"
            "See migrations/README.md for the full dev setup."
        )
    # Alembic does not support asyncpg URLs — convert if accidentally passed.
    if "+asyncpg" in url:
        url = url.replace("+asyncpg", "+psycopg", 1)
        logger.warning(
            "DATABASE_URL contained '+asyncpg'; converted to '+psycopg' for Alembic. "
            "Runtime services should keep asyncpg."
        )
    return url


def _ensure_schemas(connection) -> None:
    """Create both schemas if they do not exist.

    Must run BEFORE context.configure so the version table (in the orchestrator
    schema) can be created on first run.
    """
    connection.execute(text("CREATE SCHEMA IF NOT EXISTS orchestrator"))
    connection.execute(text("CREATE SCHEMA IF NOT EXISTS backend"))
    connection.commit()


# ---------------------------------------------------------------------------
# Offline mode — generates SQL without a live DB connection.
# Used in CI / pre-commit to audit the DDL (`alembic upgrade head --sql`).
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (--sql flag).

    Output is written to stdout as pure SQL DDL.
    Note: CREATE SCHEMA statements are emitted inline via op.execute in each
    migration; offline mode does NOT pre-create schemas.
    """
    url = get_database_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
        version_table="alembic_version",
        version_table_schema="orchestrator",
    )
    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online mode — runs against a live DB connection.
# ---------------------------------------------------------------------------


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a real Postgres connection."""
    # Override the blank sqlalchemy.url in alembic.ini with the env var.
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = get_database_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Step 1: Ensure both schemas exist before any migration op touches them.
        # This is idempotent — safe to run on every upgrade.
        _ensure_schemas(connection)

        # Step 2: Configure Alembic context.
        #   include_schemas=True  — allows ops to specify schema= on each object.
        #   version_table_schema  — places the single alembic_version table in the
        #                           orchestrator schema (Assumption A1, D-22).
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_schemas=True,
            version_table="alembic_version",
            version_table_schema="orchestrator",
        )

        # Step 3: Run the migration tree in a single transaction.
        with context.begin_transaction():
            context.run_migrations()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
